### ISSUE TITLE
Unified Login & Signup

### ISSUE THREAD

**Issue by mindgraffiti** [wordpress-mobile/WordPressAuthenticator-iOS#182]
~Duplicate the code, with storyboards and classes #187~

----

## Spike / Research
- [x] Spike: take 5 days and attempt to break apart the Login.storyboard. The purpose is to discover the feasibility of the task.

1. Remove the storyboard segues in Interface Builder and create programmatic ones.
2. Remove the IBActions in Interface Builder and create programmatic ones.
3. Remove delegates & datasources linked in Interface Builder and create programmatic ones.
4. ~Remove Scenes from Interface Builder and move to their own nibs~ (.xib)
5. Edit a ViewController and estimate how long it will take to make changes to the existing code.

----
## 0. Modify Epilogues in WPiOS.
- [x] Master issue to modify the Login Epilogue in WPiOS https://github.com/wordpress-mobile/WordPress-iOS/issues/13413
- [x] Master issue to modify the Signup Epilogue in WPiOS https://github.com/wordpress-mobile/WordPress-iOS/issues/13939

## 1. Remove known segues. Replace with navController.
- [x] remove .showLoginEmail #205
- [x] remove .showSignupMethod #225 
- [x] remove .showSigninV2 #232 
- [x] remove .showGoogle #219 
- [x] remove .showURLUsernamePassword #240 
- [x] remove .showWPUsernamePassword #245 
- [x] remove .showSelfHostedLogin  #242
- [x] remove .showWPComLogin #273
- [x] remove .startMagicLinkFlow #256 
- [x] remove .showMagicLink #254 
- [x] remove .showLinkMailView #211 
- [x] remove .show2FA #227 
- [x] remove .showDomains #260 
- [x] remove .showCreateSite #263 
- [x] remove .showSignupEmail #265 
- [x] remove .showUsernames #268
- [x] remove .showLoginMethod #270 
- [x] some segues were added manually (didn't use the enum) and need changes (these were discovered when testing a removed segue and a crash happened during the navigation attempt)

## 2. Unify the flows
- [ ] Google sign in #282
- [ ] Sign in with Apple
- [ ] WP.com login/signup
- [x] Site address #283 

## 3. Button bottom sheet UI changes
- [ ] Change "Log In" button text to "Log in with WordPress.com"
- [ ] Change that button's action to navigate to Get Started screen
- [ ] Remove the "3 button bottom sheet" from the "landing page"
