### ISSUE TITLE
UL&S: Site Address flow

### ISSUE THREAD

**Issue by mindgraffiti** [wordpress-mobile/WordPressAuthenticator-iOS#283]
#### Base UI

Create the re-usable views that will be needed in the Site Address flow.

- [x] Create a flag to enable just the unified Site Address flow #285 
- [x] Create a new blank viewController, `SiteAddressViewController` and navigate to it #293
- [x] Inside the viewController, add a tableview. Set autolayout leading / trailing margins to zero #294 
- [x] Spike: @mattmiklic requests the continue button to attach to the keyboard for regular size classes and scroll for compact size classes. Research feasibility, estimations, and impact compared to pinning the button to the bottom of the screen. #296
- [x] Create the first uitableviewcell - InstructionTableViewCell #305 
- [x] Add basic TextFieldTableViewCell #306 
- [x] Add basic TextLinkButtonTableViewCell #308  
(and renamed InstructionTableViewCell to TextLabelTableViewCell) 
- [x] Fix dynamic text bug in TextLinkButtonTableViewCell #310 
- [x] Add basic ErrorLabelTableViewCell #312 
- [x] Add support for iPad layouts. https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/334

#### Pages
- [x] SiteAddressViewController #312 
- [x] SiteCredentialsViewController #322

**Comment by mindgraffiti** [comment]
Completed after #334 was merged.

**Comment by mindgraffiti** [comment]
Re-opening because this needs Tracks

**Comment by diegoreymendez** [comment]
I updated the description above to include a link to the tracks issue.
