### ISSUE TITLE
UL&S: Sign up

### ISSUE THREAD

**Issue by mindgraffiti** [wordpress-mobile/WordPressAuthenticator-iOS#345]
### UI
- [x] Gravatar + email UITableViewCell #350 
- [x] Navigate to new UnifiedSignUpViewController #346 
- [x] ~Navigation bar, nav bar items, status bar uses correct styling after navigating from old screen~ this is blocked until UnifiedSignUpEmailViewController is built
- [x] Instruction cell, gravatar + email cell displays #348
- [x] Send Link by Email button #348

### Implementation
- [x] Send Link by Email button implementation #355
- [x] iPad support #355
- [x] Accessibility - dynamic text, VoiceOver #358
- [x] Tracks Events
