### ISSUE TITLE
Prologue Carousel: main issue

### ISSUE THREAD

**Issue by mindgraffiti** [wordpress-mobile/WordPressAuthenticator-iOS#494]
A project ticket to track prologue carousel changes.
WPiOS project ticket: https://github.com/wordpress-mobile/WordPress-iOS/issues/15056
Feature branch: https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/tree/feature/unified-prologue-carousel

### Tasks
- [ ] Implement parallaxed background
- [ ] Create individual views for each slide, use real text that can be localized instead of images as text
- [ ] Check dark mode support
- [ ] Check iPad support
- [ ] Remove feature flag
- [ ] Remove Lottie

### In Progress
- [ ] Move carousel dots to the bottom of the container
- [ ] Add placeholder views for each slide, and reposition header text

### Done
- [x] Create feature flag #497 
- [x] Update headlines #498 
- [x] Extend background behind the button view #495 

### Designs
![i5-ios-1](https://user-images.githubusercontent.com/1062444/95364944-14624300-0897-11eb-844e-aa5f2dc63401.png)
![i5-ios-dark](https://user-images.githubusercontent.com/1062444/95364953-175d3380-0897-11eb-9247-7d311e9ff3f1.png)

**Comment by mokagio** [comment]
As of [2025/02/06](https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/commit/cce14d7ea5e5af5e52cdcfa75cbec672c1603991) this repo is a public archive and no longer under development.

If you think this issue is still relevant for one or both of the former clients, please open an issue in [WordPress/Jetpack iOS](https://github.com/wordpress-mobile/WordPress-iOS/issues) and [WooCommerce iOS](https://github.com/woocommerce/woocommerce-ios/issues)

Thanks!
