### ISSUE TITLE
Google SignIn without SDK – What's left to do

### ISSUE THREAD

**Issue by mokagio** [wordpress-mobile/WordPressAuthenticator-iOS#741]
- [x] Merge the `OAuth` folder into `GoogleSignIn` – _Do this at a point when there are no other files likely to be added, to avoid conflicts_ – See #750
- [x] [Update `OAuthRequestBody` to init with a `CodeVerifier` parameter](https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/740#discussion_r1110440264) - https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/745
- [x] Finish wiring the pieces together. See https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/743
- [x]  Experiment to find the minimal valid `scope` to use. – https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/756
- [x] Address the feedback in #714 and write UI tests – _Blocked because sign in now requires MFA_
  - [ ] ~~Add UI tests for the various other user scenarios—this is trickier because I don't yet know how to generate dummy Google account users with or without WordPress.com connection to test the flows~~
- [x] [Validate the JWT used to create the ID token](https://developers.google.com/identity/openid-connect/openid-connect#validatinganidtoken) – Not needed. See internal ref paaHJt-4H3-p2
- [x] Ship behind remote feature flan in Jetpack/WordPress, see https://github.com/wordpress-mobile/WordPress-iOS/pull/20128
  - [x] Fix new accounts not having email in `WPAccount` object - https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/issues/759
  - [x] Add tracks logs – N.A. Logs are already available

**Comment by mokagio** [comment]
All done now. The client apps are already pointing to the 7.0.0 beta version.

- https://github.com/wordpress-mobile/WordPress-iOS/pull/21344
- https://github.com/woocommerce/woocommerce-ios/pull/10483
